name: docker build and publish

on:
  push:
    branches: [main, dev]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: define image tag
        run: |
          echo GITHUB_REF_NAME=$GITHUB_REF_NAME
          [ "$GITHUB_REF_NAME" == "main" ] && IMG_TAG=latest
          [ "$GITHUB_REF_NAME" == "dev" ] && IMG_TAG=dev
          echo IMG_TAG=$IMG_TAG
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: felixlobert/force-sar:$IMG_TAG
